import type { Metadata } from "next";
import { Poppins, Roboto, Inter, Montserrat, Nunito } from "next/font/google";
import Script from 'next/script';
import './globals.css';
import { TranslationProvider } from "./hooks/useTranslation";
import { CookieConsentBanner } from "@/components/CookieConsentBanner";
import { Toaster } from 'react-hot-toast';
import { SecurityCleanup } from '@/components/SecurityCleanup';

// Body fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

// Heading fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${roboto.variable} ${inter.variable} ${montserrat.variable} ${nunito.variable} antialiased font-sans`}
      >
        {/* Google reCAPTCHA v3 Script - Inline */}
        {process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY && (
 <Script
          strategy="beforeInteractive"
          src="https://www.google.com/recaptcha/api.js"
        />
        )}
        <TranslationProvider>
          <SecurityCleanup />
          {children}
          <CookieConsentBanner />
          <Toaster 
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: 'var(--background-card)',
                color: 'var(--text-primary)',
                border: '1px solid var(--input-border)',
              },
              success: {
                iconTheme: {
                  primary: '#10b981',
                  secondary: 'var(--text-primary)',
                },
              },
              error: {
                iconTheme: {
                  primary: '#ef4444',
                  secondary: 'var(--text-primary)',
                },
              },
            }}
          />
        </TranslationProvider>
      </body>
    </html>
  );
}
